apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipelines
data:
  pipeline1.conf: |
    input {
      beats {
        port => 5045
      }
    }
    filter {
      # Your custom filters for pipeline 1
    }
    output {
      elasticsearch {
        hosts => ["elasticsearch-master:9200"]
        index => "hop-dev-%{+YYYY.MM.dd}"
      }
    }

  pipeline2.conf: |
    input {
      beats {
        port => 5046
      }
    }
    filter {
      # Your custom filters for pipeline 2
    }
    output {
      elasticsearch {
        hosts => ["elasticsearch-master:9200"]
        index => "hop-prod-%{+YYYY.MM.dd}"
      }
    }

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logstash
spec:
  serviceName: logstash
  replicas: 2  # Adjust as needed
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:7.15.2
        volumeMounts:
        - name: logstash-config
          mountPath: /usr/share/logstash/config
        - name: logstash-pipelines
          mountPath: /usr/share/logstash/pipeline
      volumes:
        - name: logstash-config
          configMap:
            name: logstash-config
        - name: logstash-pipelines
          configMap:
            name: logstash-pipelines
---
apiVersion: v1
kind: Service
metadata:
  name: logstash-logstash
spec:
  selector:
    app: logstash
  ports:
  - name: beats-prod
    port: 5046
    targetPort: 5046
  - name: beats-dev
    port: 5045
    targetPort: 5045

